name: dead reckon
favicon: null
layout_spectrum: 0.19215879426337779
typography_spectrum: 0.3840136860962957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9346514153294265
  lightness: 0.9045009301044047
  saturation: 0.102111253188923
  rhythmicContrast: 0.8626044802367687
purpose: []
